name: Demo Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Version tags"

  # push:
  #   branches: [main]

env:
  VERSION: 0.9.0
jobs:
  demo-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.TOKEN }}

      - name: Copy source for distribution
        run: |
          cp -r . ../dist
          rm -rf ../dist/.git

      - name: Copy source to development
        run: |
          cp -r ../dist ./docker/development/app 
          cp ./online-demo.env ./docker/development/app/.env

      - name: Get Version
        run: |
          echo VERSION=$(cat ./app.yao  |grep 'version' | awk -F '"'  '{print $4}')  >> $GITHUB_ENV

      - name: Check Version
        run: echo $VERSION

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: hub.iqka.com
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Development
        uses: docker/build-push-action@v5
        with:
          context: ./docker/development
          platforms: linux/amd64
          push: true
          tags: hub.iqka.com/max/yaoweb:${{ env.VERSION }}-amd64-dev

      # https://yaoweb.iqka.com
      - name: Deploy Development
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 139.199.30.36
          port: 22
          username: root
          command_timeout: 30m
          key: ${{ secrets.SSH_KEY }}
          script: |
            /data/docker/bin/deploy.sh max yaoweb ${{ env.VERSION }}-amd64-dev hub.iqka.com
            docker exec yaoweb sh -c 'yao migrate --reset --force'
            docker exec yaoweb sh -c 'yao run scripts.test.Data'
